version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./srcs/database:/var/lib/postgresql/data
 
  backend:
    build: 
      context: srcs/backend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:3000"
    container_name: backend_container
    depends_on:
      - database

  frontend:
    build: 
      context: srcs/frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "80:80"
      - "443:443"
    container_name: frontend_container
