version: '3'
services:
  database:
    image: "postgres"
    hostname: 127.0.0.1
    ports:
      - "5432:5432"
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./srcs/database:/var/lib/postgresql/data
  backend:
    build: ./srcs/backend/Dockerfile
    image: frontend
    hostname: 127.0.0.1
    ports:
      - "3000:3000"
    container_name: frontend_container
